In [63]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [64]:
df=pd.read_csv(r"C:\Users\ABC\Documents\archive (3)\Crop_recommendation.csv")

In [33]:
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [66]:
df.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [34]:
df.shape

(2200, 8)

In [35]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [37]:
df['label'].value_counts()

rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: label, dtype: int64

In [38]:
x=df.drop('label',axis=1)
y=df['label']

In [39]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
dtypes: float64(4), int64(3)
memory usage: 120.4 KB

In [40]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2200 entries, 0 to 2199
Series name: label
Non-Null Count  Dtype
--------------  -----
2200 non-null   object
dtypes: object(1)
memory usage: 17.3+ KB

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2)

In [42]:
x_train.shape

(1760, 7)

In [43]:
x_test.shape

(440, 7)

In [44]:
y_train.shape

(1760,)

In [45]:
y_test.shape

(440,)

In [46]:
from sklearn.linear_model import LogisticRegression

In [47]:
model=LogisticRegression()
model.fit(x_train,y_train)

c:\Users\ABC\Nishabi\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [48]:
y_predict=model.predict(x_test)

In [49]:
from sklearn.metrics import accuracy_score
logi_reg_acc=accuracy_score(y_test,y_predict)
print("logistic accuracy is:"+ str(logi_reg_acc))

logistic accuracy is:0.9704545454545455

In [50]:
from sklearn.tree import DecisionTreeClassifier

In [51]:
model2=DecisionTreeClassifier()
model2.fit(x_train,y_train)
y_predict2=model2.predict(x_test)

In [52]:
D_acc=accuracy_score(y_test,y_predict2)
print("Decision tree accuracy is:"+str(D_acc))

Decision tree accuracy is:0.9954545454545455

In [53]:
from sklearn.ensemble import RandomForestClassifier
model3=RandomForestClassifier()
model3.fit(x_train,y_train)
y_pred4=model3.predict(x_test)

In [54]:
R_acc=accuracy_score(y_test,y_pred4)
print("Random forest tree is:"+ str(R_acc))

Random forest tree is:0.9977272727272727

In [55]:
import joblib

In [56]:
filename ='model.pkl'

In [57]:
app=joblib.dump(model2,"model.pkl")

In [58]:
app=joblib.load("model.pkl")

In [59]:
arr=[[90,42,43,20.879744,82.002744,6.502985,202.935536]]
y_pred5=app.predict(arr)

c:\Users\ABC\Nishabi\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [60]:
y_pred5

array(['rice'], dtype=object)